---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mosquitto-passwd
  namespace: monitoring
spec:
  encryptedData:
    passwd: AgBEhzsiD9oHieLugR4lmN45qO+gqcZD+I6scbSbJByyGP6UdgaLKY1EI14UqB6wmaxbc+1x2nrcU3bEva4Hv6UYNnNRaGF+Q97iFVehIZYT55lP4mLeRh+0KTjdQirIVoy7DbRXWI2SM3ICQkNDh4LvN0j6QwSAao43aq67XKwKT4K6ir/v4wWXA35flDzq6ROs3lDK4IuWnT/ceQzRJpDAz0eLA/VPTHmx1m5TrAE36ozk/hvWcQiPdU6fyW6ruxekda75dbtlPj5UUPnRjL33L53ks3eFAMqm/haGYLo6PZdgC9bsdl7pG4KXR9STEJ6ELbvoJWvw/gUUtqRa7qZbYtChxXfJ3qRP9Uei4T7JtfV0u2Ov8P/wum38WW7QuFqHkrScT7iXfdj8PdDgL02yVB1J3M0NS2xb5ieFJGKOzUzILLwNBuoi6G1oy7KrIP1cx2us+nblU4ZVRkqJL4/BFBoJCITIZXNLb7fB7zmB8YmU2daIyE4txzRSNQxDah1NL8Yvxz7FoTmlo3FJcza4dp2dixyuAEx3hay+cUKD5EV5tBGFE0x00W2Z+ekOqPr2uxDGySh/hIcyWTWGrY1nIODGb9GnG6zBkDGjnTZ28h5535nv9FKONzkY1hhVzRsL2qifjT5NEOspqaIO7lDOL1zXktXtSlpH6gr+n//0ojDZcvZOBQfVfskNoewIXg2eTfrJn4LzH0/gFt61eHInSwjWYI5c9yWXKcOo1Niy1uz7gg9tU8T226Mbi18iKjM86LZ2qOfBvpR3Pai5ZAoDU8idMULZOiezGz2Et5+KE3+MBKumSwWtJMXPeI8yHOE508VqS0IL8k7rPr5GWyXKSh7TIrutJnFDCrymlWS5tjVoFs0TLkPJYTvePVZ538o3pdU4/P8qa7atoDQVDo948Vhzx/hjEXnUC/f7PN4WF3h6LBCvPwtCHvh9PemUeMqKdN2DAlf8MpwispWKG/J1+Y+dgBEmEv4QmDjFhjLetuqf0ORD0j5a4LGUml+gGdmU6g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mosquitto-passwd
      namespace: monitoring
    type: Opaque
