---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mosquitto-passwd
  namespace: monitoring
spec:
  encryptedData:
    passwd: AgA+imhgnNUbZGlUrbBrJQ3dqWHDS12yyprd4LbaRJ6t3VDVPuqrqLg27cG5IlIPLHjebgjaCi+qTHtUkZzpZ0DQWN5GkVqdP4hS9PZRcVdcplQXViddiOZAopUSpI92F+N+K/bLrkhAKTAck8+iM2xPtrw0AlHqceNwKM/UcIo/t+JHCqJRhCoVgarzuZoK7oXK0InM87CfztYusv5f7p+4w5YB5exHUd73yJ+sMRX+iKTreECW1iJDSMti5kAH0pdS71Gc6yQM7hlD91QwC0HzDUOA9AiRdLtUJ0mDlSz88FmgbYe2inCQeo91nFOOiV6F5br0n8E/mZ+6Om1g5DsGv20Gt036wmuERcSJgM99+WT4g55tfu3LBknjEFDccsP8nyzkq0djVDE6xTLphVZOvwqkoWBNejGMpd9VlURji1ICmrPWWF1Gu7uGkXlfvPbNjnzmdBhINxKBILhGVg+uCP6JWrcB9QE0tDKuEkzQxUX+IKnmocudOWuFK3Cp/tgEdc5LGtUNNQRfMXvkjyVkmGLW25ZPBIOj6wudKuTvoVsLQ9XawxZJUmvGeWTzkyxWRieeWia+ZVs+HODBnd4Ys1QFcou09mZnD+sOGa3bFPw/bfPCdlyuIUtinXXajrSh+G7m9rihASaWWgtd0KB5vGH7ekYensTrLaW8WVkqlMFEBBALJYkrvO/sn4QwoXQZqOohQPLu9oVsSCsOAOQMVQd/pWAKHUz6zT7dbLMkUIbFgdDqjteSaJvQdXRZj0XDsXD9oVld7RYMWsbGVs81wziKx7wBb4h1Vkrb5QBEUlTfNNN6Z3jRrIboX7uYgNhPTWN5Y1uVx7luh3T9F0CK+YNDAc5PYsrv8HuEdLgcK/gKdIOdyxGuLZEyCn8Lrw8G1qiC3oo61mD59V+Xphy4jmWu8NhEVdWz+eG2tPez1g3zsRox23mbFOzLj9Bomhul+FisnY4gsRF62t6aP4oMChStyKwElCNdXmMzp5YsLZn1SJDFXTB0HvURLfm2qF2ZN9U8g6xjJpVkiQgzFaX/t7uq8ZgSJWU5/oT4RR58Zk3y8OKkCOBGV7loW015RODi7/L3c4cKmNBc2T8SvQlvmyZk/7KV9XWMiwKP/uyIJqdmy9NPiIScMo6+ESDVxvtfXjrn/dn9WzqHm0pbv52KVPC+ofHF1IiFB3SFKF0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mosquitto-passwd
      namespace: monitoring
    type: Opaque
