---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mosquitto-passwd
  namespace: monitoring
spec:
  encryptedData:
    passwd: AgBqm7A0EAZxydfFkc2uQYV3KWpiOgUG+yoI+OzDLqeDTAbs3RAeIJt7U15RiMkR5Q1ZReQsu3aYsj9iNxRYy7wCOKaH5n0lshejMI4EOVB2hT/qDabM9cN/nnnDRy/5Pk9GtHLH/coTNKzI6i4SDHy3D3Fn9qyoKWzMnzqGzAnxQVKyCtgSGn10a85B7P8jXU5BsAGdJKv3lYVdouLBu+mS+n8tdAn6CKz/AQEP5hVGRP9F9LuOzDws3Xzx67KqwZCnkS+xjRoTQts3KGdTV43zTGxiYNYcpKaAiqmV03X78bkYAiPB4Z7eFt1yUcBa2y1LQSDmZXcgbzrfUwRz4JkTRiIvSb0EzMiP9AOji/JSNbCuuiTXpwXJ+BJwnLKz1E8yD8pzSByOjy0xPOcb7HzMUVbncVO0m6mdBXcdwuLefztT6VMluxbU/oJQUhpGkIseBqWmV42awbCuoh3n+eN50fa2ckoWehroQAygcSDxsk92kPrSi5JBEJp3Wl7ShMH78KD0OEnkfTbod3EyuzIr3WRIHlAdGnpT+LPkg5NYLyCUco9AcbX/TxVTm8//xUpAIp+h5yRgii9GW7V3DufJQO03hUE8ZlkwNZpIDWY3FJOH5Txdf/9peXBtrASHvt6LAlMPgCszBXKOFF4GhdpjrXmVV0M3XbXwaj5FjEMEIcDBen+Kym0jqgMgm8qu3cQR4sJ11g5Y2AkR7jEzt3EriisUsISnIT5hEGT9yeSahCuV048tldbm6UrtManur2aVh0Bde/5kP+Qdmjylkv7qt89fSxQl0S+ZDTBHpC4so++1h+J+z5bCTEuM6vtRbP4Ph2WrDM7pBFfdGaQKSJV5VnAJlDzXCiaquw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mosquitto-passwd
      namespace: monitoring
    type: Opaque
