---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: meshmonitor-env
  namespace: mesh
spec:
  encryptedData:
    SESSION_SECRET: AgAFarUZiRsiKBytdl0nLwSgqZZnr2VW4OfY4iRksCSaMvl2YVFIoqIEvTUhllMTbbYXzUhxWKfwsJirZ+05sieJ/8NDpj8wGeLjnM6YXiSsqHOHxNAEUafK6p6wXJhgP0exiuYtldZdUAv8ficbXU0BlfdP02mj3LXimW3Wx38u5zJF5PzMK2Ei2fCa4XulbOjepi+N8YxRKoH3iGBDgbEPpmOIeDKQhFl9LYD60yAIsD5L35qSZh8ulWvbtTVBXyTCJzuVU7jdm5D0MwLAH4x1IuJNp5rHI195NT1050s2pnI3bFyAnf7h9MuEATr0A+ITeSs9Xn4+y2bobZO9OlaB6ThZtV2KzGTBiQ1pDR+efZT0zrCk6v4ScVhQxZBr7Hvo9bSMkhoRSSQm+AHcMJ0ydpX64tLeje4yGcrGFgqpFesWcPAlP9UK3s4aWWJ5uan4nvswRfrEoM32AmavEqSyCWFwErCZqK5y1LWVFsNFq/ULFUIOOUOj7NV5A0X/XSwAqtdajocX1v4Af2OqaXL6wUN2AmFGHsFf7pIBJ3SR8JmdF5Iu/Q/dN+xkiunH6js3IbETg02ZlnOyTW2drmn6yqqF2y34w7LxpFC7hF0ytuZjwllPJIh2JSnjKJQ/hSfvkmXy9yI/6V78l9b6+sQvnqnL8xIq6hNLmnBI+N8pVl8UGZSZJnojg7zQsidbbqn9LOYOMnaQ3pFHwSZIL19origPBO7h1I91dLwHrjoTytLNVzwpbWgqHNTE9g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: meshmonitor-env
      namespace: mesh
    type: Opaque
