---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: meshmonitor-env
  namespace: mesh
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgAofmYAMEJ+55+6Wn8UbYATrJr/Mv3CP9Xi5PVU6B3oa8wHev8tllKd7R9fDi8CRipNExzCVLCl1HUjdgVkzr0ohdcpV5S1OVlxoOV7Ym7ZZOE+n1Q7w4SCqmAfdYxmRebH8Ovv068KfqyOigD2mw9UOdA6WGeUCza2I2WUAQOp6cVFBcM6Vl/gAWEGdHzDr+T2g8JAma1nby476Dq7RSO+TCtw3W2RGoyhyXNr5hGPucZqBmJ/HDL3yG14T6fLOBC3cF1QsD4HATBMmD0OxBxz1GLQo4jkajZFQKgAeYR+J8iODezX1vPGD8+R+bJw5aBJ1XeA/3h8YAKZ3E3Y35v6ZlsVIVh4u5ZqTOxedfOGUGZW3RxJmm3b4+AzmDz1twLSSgUmsHIpAS0YzsLSLXhSZi7cnAFgymqTLtVwPcm0/GQtM16kHmR4zpiueceDJAAFY4mLraRVNrziaSGlf0SKvi727hEht7zRttw3f+NbVRGNbKFxv8VS0H/agrwT8qj1nx/GAruo9ehdPz0jriKzKCyFE4y9ho30fr5USYtP6JzhPjMeKV382tAVM2Zdwxj9/VfQClIuqltsx2ffhlvOKdi/O6W6AeXpyLcPDGhfyrR6NOYyLasObWGamTnUpgKn4eooVDq+LPENLPYbjxjQ+gEWkt0ug+gR1ttjmvZyPmdAk2CcNDzsSDi16xTWF9ivpuhv/jnlLa5zDZIJl7CdZp8bPJbqBTqyPl/SOhHan5gxwK76UJNRMEpMTv+VJvXd9z88XkgQTdO5S5+3RxvldTK5+OHuRpOjjaKSQcugd1MLL1JgzQoOy1/DnQJ2gT3EZP0Rt1h1pmhL7ByHy7xTm/qWhnK8qhdtmEiMjdf2Pg==
    SESSION_SECRET: AgAfe2WTq73a/AwVY0ms0+x8jGHz1hymkrAdvG9WuN5Y1kavcSDHR85bjDGBLqyjv/zkBiHIs5KA4etCPupvw1u8/jivAF5yY82kWFFRQlurKV5DkOdZl3vcaJ7QcekwiCO7Mjf7DvWQVm8nroP+S0yKYkiRQrfHv8CPesGes2hHExwxsqj11NfL396vyO0RG9zr3b9kcD0i4o763A4mkQMXJ0VMk+Ja9Jba2AWwWEZ3er/mATxxRuJBcxSp2BTBmg2BWv+v0Gc8AhHHFy2/L8/V4m8ec07hl5ik8vPuDSNeyg2jS3CWNCEBCIWyYYZAiWHiM/e9vqaKBG214/xv7SYaMd/L3+EEWiT2PktPY04AOGje5bk16PN/GD1NhBaNFkkrYfXs7cXc7p2M9EnBHac/PDVcRqqDmSHoPHn3EiCS6W4U8/cYZIuzg3MwMiR7+3Czr1LZNQzypfFO6c1z2yBTaDhLQlDBHhoXgQCwsId6elUJClubEsES3d+jPe9dxYFEEoGXt4N4L4NufdU+M+C8hCyC4OlxgrmiW4G22uGxaKB2XcAjhV86ls0Smo8nomBfMFutyzogg9LqSv1OXlRHIQKgxjGSJuEqc814hwPPCz20Q7dSIgoWinT1/wq9ejQsLds4G/acewMJgJCGSVzjFosg+CbD9Wco7F4YifWhbYbp6yvD164UaPcRwP/nyrvXyq215E+/iThoSB1MO7kNsy9auzFlLGq6yDQwn8MKQnPxh/RyrMhX0bY1vw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: meshmonitor-env
      namespace: mesh
    type: Opaque
