---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cluster
spec:
  encryptedData:
    cloudflare-token: AgDTK5yapHz6Cbk3mXDS/01J15ngb5SguAV3nzXVHSTacql7q36snQf11L1udGDzJCQnXet2ImIUpHiIRF1m73xqUt9rhUAJiuHjcmnscZywwl/7URKnG0Rqben4Z1Au5lkYgH1Ev0yvo6U9kdbo+coLnqR/t9U07hpQK7I3UfuOFZ8j/bCoKWydyNOA3wmpmbp+UaN2Tj2CQSnOSIckbJZVrkZRMdCgQHDBr+qNq1hxZ9/EFw6VWi9tagB135p5wmm+mrnK8rSOvGOR6bBpykayXlzOhzZuk5YuQba7gTQcbtvNxVwe30OMM37+JfaD7I++I1rSPRIqS5iR6qJMXcBeWzmIyLwZvhWHONVqymHtkXSH4ntHX2HxwNKtreyjYBfMIdCOBRUf98zVUOmTaFzNgH+IiZkAr7tFYSe/f/okzEmUIlKygW0BBjpuOCESx0/vm+Tsvtc1b1XFD8DOaET1h4xB8RZOIlLGBgkD8vIH12CsWADKlEmCj8kNFVCUaHOaxbpo6gZRv17vNUArZX/9FswNjCcVmIl+D7FizdPc8uNUKJx+hhSsIWTL+QDy5c0U7EKPVkOzVnFwTQ99knaNkK9XV19qx/RKKyHymMCNiNKKklM1rKw+Y1eedREQY9Yt/va4Z87SprsLqCVN3oRJn/zkgkJXfvAE1WGk9fuDb1IdICsyes/t6uNmtrBdkW5NHqtUOkYbjoDhrwX8hDnBPQX5d1CGQRmixXHmA7I1iuRq7U2RIuws    
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cluster
    type: Opaque
  